name: "godot-ci export"
on: [workflow_dispatch, push]

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.7.3.rc1
  EXPORT_NAME: Mario-Forever-Community-Edition
  PROJECT_PATH: .
  UPLOAD_FOLDER: MFCE-Builds

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04 # Using 24.04 due to libgdmpt extension (for audio playback) failing on 22.04
    container:
      image: jue13/godot-ci:4.7.3.rc1
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      # - name: Set WINEPREFIX
      #   run: echo WINEPREFIX=/root/.wine >> "$GITHUB_ENV"
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
          echo EXPORT_DIR="$(readlink -f build)" >> $GITHUB_ENV
      - name: Project Import
        run: |
          cd $PROJECT_PATH
          godot --headless --import
      - name: Windows Build
        run: |
          cd $PROJECT_PATH
          echo "interim-win64\n${{ github.sha }}" > stages/main_menu/version-text.txt
          printf "extends RefCounted\n\nconst DEBUG_ENABLED = true\n" > engine/singletones/nodes/debug/enable_debug.gd
          mkdir -v -p "${{ env.EXPORT_DIR }}/windows"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3' > "${{ env.EXPORT_DIR }}/windows/01. Compatibility Mode.bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3_angle' > "${{ env.EXPORT_DIR }}/windows/02. Compatibility Mode (angle).bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" -- --developer-commands' > "${{ env.EXPORT_DIR }}/windows/03. Debug Mode.bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3 -- --developer-commands' > "${{ env.EXPORT_DIR }}/windows/04. Debug, Compatibility Mode.bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3_angle -- --developer-commands' > "${{ env.EXPORT_DIR }}/windows/05. Debug, Compatibility Mode (angle).bat"
          godot --headless --export-release "Windows Desktop" "${{ env.EXPORT_DIR }}/windows/$EXPORT_NAME.exe"
      - name: Checkout Skins
        uses: actions/checkout@v7
        with:
          repository: meteo-dream/bundled-mfce-skins
          path: build/windows/temp_skins
      - name: Prepare For Upload
        run: |
          echo "MFCE Build: [$(echo "${{ github.sha }}" | cut -c 1-7)](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) from $(date '+%d-%b-%Y %T')" > "${{ env.EXPORT_DIR }}/README.md"
          cd ${{ env.EXPORT_DIR }}
          mv -v windows/temp_skins/* windows
          rm -rf windows/temp_skins
          cp README.md windows/Readme.md
          rm -f windows/LICENSE
          rm -rf windows/.git
          zip -r build_windows.zip windows
      - name: Upload to Cloudreve
        uses: bxb100/action-upload@v0
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.CLOUDREVE_URL }}
            username=${{ secrets.CLOUDREVE_USERNAME }}
            password=${{ secrets.CLOUDREVE_PASSWORD }}
            root=/${{ env.UPLOAD_FOLDER }}
          include: |
            '${{ env.EXPORT_DIR }}/build_windows.zip'
            '${{ env.EXPORT_DIR }}/README.md'
  
  export-linux:
    name: Linux x86-64 Export
    runs-on: ubuntu-24.04 # Using 24.04 due to libgdmpt extension (for audio playback) failing on 22.04
    container:
      image: jue13/godot-ci:4.7.3.rc1
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
          echo EXPORT_DIR="$(readlink -f build)" >> $GITHUB_ENV
      - name: Project Import
        run: |
          cd $PROJECT_PATH
          godot --headless --import
      - name: Linux Build
        run: |
          cd $PROJECT_PATH
          echo "interim-amd64\n${{ github.sha }}" > stages/main_menu/version-text.txt
          printf "extends RefCounted\n\nconst DEBUG_ENABLED = true\n" > engine/singletones/nodes/debug/enable_debug.gd
          mkdir -v -p "${{ env.EXPORT_DIR }}/linux"
          echo '#!/bin/bash\n\n"./${{ env.EXPORT_NAME }}.x86_64" -- --developer-commands' > "${{ env.EXPORT_DIR }}/linux/Debug Mode.sh"
          chmod +x "${{ env.EXPORT_DIR }}/linux/Debug Mode.sh"
          godot --headless --export-release "Linux/X11" "${{ env.EXPORT_DIR }}/linux/$EXPORT_NAME.x86_64"
      - name: Checkout Skins
        uses: actions/checkout@v7
        with:
          repository: meteo-dream/bundled-mfce-skins
          path: build/linux/temp_skins
      - name: Prepare For Upload
        run: |
          echo "MFCE Build: [$(echo "${{ github.sha }}" | cut -c 1-7)](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) from $(date '+%d-%b-%Y %T')" > "${{ env.EXPORT_DIR }}/linux/README.md"
          cd ${{ env.EXPORT_DIR }}
          mv -v linux/temp_skins/* linux
          rm -rf linux/temp_skins
          rm -rf linux/.git
          zip -r build_linux.zip linux
      - name: Upload to Cloudreve
        uses: bxb100/action-upload@v0
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.CLOUDREVE_URL }}
            username=${{ secrets.CLOUDREVE_USERNAME }}
            password=${{ secrets.CLOUDREVE_PASSWORD }}
            root=/${{ env.UPLOAD_FOLDER }}
          include: |
            '${{ env.EXPORT_DIR }}/build_linux.zip'
