name: "Release Builds"
on: workflow_dispatch

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.7.3.rc1
  EXPORT_NAME: Mario Forever Community Edition
  PROJECT_PATH: .
  UPLOAD_FOLDER: MFCE-Builds/Release

jobs:
  export-windows:
    name: Windows x86-64 Release Export
    runs-on: ubuntu-24.04 # Using 24.04 due to libgdmpt extension (for audio playback) failing on 22.04
    container:
      image: jue13/godot-ci:4.7.3.rc1
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      # - name: Set WINEPREFIX
      #   run: echo WINEPREFIX=/root/.wine >> "$GITHUB_ENV"
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
          echo EXPORT_DIR="$(readlink -f build)" >> $GITHUB_ENV
      - name: Project Import
        run: |
          cd $PROJECT_PATH
          godot --headless --import
      - name: Windows Build
        run: |
          cd $PROJECT_PATH
          mkdir -v -p "${{ env.EXPORT_DIR }}/windows"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe"' > "${{ env.EXPORT_DIR }}/windows/00. Launch in Recommended Mode (D3D12).bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3' > "${{ env.EXPORT_DIR }}/windows/02. Launch in Compatibility Mode (OpenGL3.3).bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3_angle' > "${{ env.EXPORT_DIR }}/windows/03. Launch in Compatibility Mode (ANGLE).bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver vulkan' > "${{ env.EXPORT_DIR }}/windows/01. Launch in Alternative Mode (Vulkan).bat"
          godot --headless --export-release "Windows Desktop" "${{ env.EXPORT_DIR }}/windows/$EXPORT_NAME.exe"
      - name: Checkout Skins
        uses: actions/checkout@v7
        with:
          repository: meteo-dream/bundled-mfce-skins
          path: build/windows/temp_skins
      - name: Prepare For Upload
        run: |
          echo "MFCE Release Build: [$(echo "${{ github.sha }}" | cut -c 1-7)](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) from $(date '+%d-%b-%Y %T')" > "${{ env.EXPORT_DIR }}/README.md"
          cd ${{ env.EXPORT_DIR }}
          mv -v windows/temp_skins/* windows
          rm -rf windows/temp_skins
          rm -f windows/LICENSE
          rm -rf windows/.git
          zip -r mfce_windows.zip windows
      - name: Upload to Cloudreve
        uses: bxb100/action-upload@v0
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.CLOUDREVE_URL }}
            username=${{ secrets.CLOUDREVE_USERNAME }}
            password=${{ secrets.CLOUDREVE_PASSWORD }}
            root=/${{ env.UPLOAD_FOLDER }}
          include: |
            '${{ env.EXPORT_DIR }}/mfce_windows.zip'
            '${{ env.EXPORT_DIR }}/README.md'
  
  export-linux:
    name: Linux x86-64 Release Export
    runs-on: ubuntu-24.04 # Using 24.04 due to libgdmpt extension (for audio playback) failing on 22.04
    container:
      image: jue13/godot-ci:4.7.3.rc1
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
          echo EXPORT_DIR="$(readlink -f build)" >> $GITHUB_ENV
      - name: Project Import
        run: |
          cd $PROJECT_PATH
          godot --headless --import
      - name: Linux Build
        run: |
          cd $PROJECT_PATH
          mkdir -v -p "${{ env.EXPORT_DIR }}/linux"
          printf '#!/bin/bash\n\n"./${{ env.EXPORT_NAME }}.x86_64"' > "${{ env.EXPORT_DIR }}/linux/00. Launch in Recommended Mode.sh"
          printf '#!/bin/bash\n\n"./${{ env.EXPORT_NAME }}.x86_64" --rendering-driver opengl3' > "${{ env.EXPORT_DIR }}/linux/01. Launch in Compatibility Mode.sh"
          chmod +x "${{ env.EXPORT_DIR }}/linux/00. Launch in Recommended Mode.sh"
          chmod +x "${{ env.EXPORT_DIR }}/linux/01. Launch in Compatibility Mode.sh"
          godot --headless --export-release "Linux/X11" "${{ env.EXPORT_DIR }}/linux/$EXPORT_NAME.x86_64"
      - name: Checkout Skins
        uses: actions/checkout@v7
        with:
          repository: meteo-dream/bundled-mfce-skins
          path: build/linux/temp_skins
      - name: Prepare For Upload
        run: |
          cd ${{ env.EXPORT_DIR }}
          mv -v linux/temp_skins/* linux
          rm -rf linux/temp_skins
          rm -f linux/LICENSE
          rm -rf linux/.git
          zip -r mfce_linux.zip linux
      - name: Upload to Cloudreve
        uses: bxb100/action-upload@v0
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.CLOUDREVE_URL }}
            username=${{ secrets.CLOUDREVE_USERNAME }}
            password=${{ secrets.CLOUDREVE_PASSWORD }}
            root=/${{ env.UPLOAD_FOLDER }}
          include: |
            '${{ env.EXPORT_DIR }}/mfce_linux.zip'
